// AUTH STORE
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_AUTH_ERRORS = "SET_AUTH_ERRORS";
export const REFRESH_USER = "REFRESH_USER";

// APP STORE
export const IS_LOADING = "IS_LOADING";
export const IS_MENU_OPEN = "IS_MENU_OPEN";
export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
export const SET_PAGE_CTA = "SET_PAGE_CTA";

// DATA STORE
export const GET_DASHBOARD = "GET_DASHBOARD";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const GET_CONTACTS = "GET_CONTACTS";
export const GET_LICENSES = "GET_LICENSES"
export const GET_ALL_FAQS = "GET_ALL_FAQS";
export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
export const GET_ALL_WARRANTIES = "GET_ALL_WARRANTIES";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ALL_ORDERLINES = "GET_ALL_ORDERLINES";
export const GET_ALL_CERTIFICATS = "GET_ALL_CERTIFICATS";
export const GET_ALL_BLOGS = "GET_ALL_BLOGS";
export const POST_TICKET_COMMENT = "POST_TICKET_COMMENT";
export const POST_WARRANTY_COMMENT = "POST_WARRANTY_COMMENT";
export const OPEN_WARNING_MODAL = "OPEN_WARNING_MODAL";
